---
sidebar: sidebar 
permalink: rest-core/url_format.html 
keywords: url, url format, endpoint, version 
summary: REST API を使用したリソースインスタンスまたはコレクションへのアクセスに使用される URL の一般的な構造は、いくつかの値で構成されます。この構造は、基礎となるオブジェクトモデルとシステム設計を反映しています。 
---
= URL 形式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST API を使用したリソースインスタンスまたはコレクションへのアクセスに使用される URL の一般的な構造は、いくつかの値で構成されます。この構造は、基礎となるオブジェクトモデルとシステム設計を反映しています。

.root としてアカウントを作成します
すべての REST エンドポイントへのリソースパスのルートは Astra アカウントです。そのため、URL内のすべてのパスはで始まります `/account/{account_id}` ここで、 `account_id` は、アカウントの一意のUUIDv4値です。内部構造：すべてのリソースアクセスが特定のアカウントに基づいている設計を反映します。

.エンドポイントリソースカテゴリ
Astra リソースエンドポイントは、次の 3 つのカテゴリに分類されます。

* コア (`/core`)
* マネージドアプリケーション (`/k8s`)
* トポロジ (`/topology`)


を参照してください link:../endpoints/resources.html["リソース"] を参照してください。

.カテゴリバージョン
3 つのリソースカテゴリのそれぞれに、アクセスされるリソースのバージョンを制御するグローバルバージョンがあります。規則および定義により、リソースカテゴリの新しいメジャーバージョン（例えば、から）に移動します `/v1` 終了： `/v2`）を使用すると、APIの変更が破棄されます。

.リソースインスタンスまたはコレクション
リソースインスタンスまたはコレクションにアクセスするかどうかに基づいて、パスでリソースタイプと識別子の組み合わせを使用できます。

.例
* リソースパス
+
上記の構造に基づいて、エンドポイントへの一般的なパスは次のとおりです。 `/accounts/{account_id}/core/v1/users`。

* 完全な URL
+
対応するエンドポイントの完全なURLは次のとおりです。 `\https://astra.netapp.io/accounts/{account_id}/core/v1/users`。


